2017-03-01 12:43:14,733  - INFO - url of sheet which we are hitting {'https://docs.google.com/spreadsheets/d/1TnhTtkISzPJvWOL06PnsVet7lcJEBbqjF7SeXLXH4jo/edit#gid=0': {'NOMBRE': 'test2'}}
2017-03-01 12:43:14,733  - INFO - URL from which we are getting list of accounts:{'https://docs.google.com/spreadsheets/d/1TnhTtkISzPJvWOL06PnsVet7lcJEBbqjF7SeXLXH4jo/edit#gid=0': {'NOMBRE': 'test2'}}
2017-03-01 12:43:21,447  - INFO - Connected to drive
2017-03-01 12:43:21,448  - INFO - Connected to google drive

2017-03-01 12:43:25,009  - INFO - List of accounts ['2809296861', '7813355720', '4804168647', '2231303651', '5689562067', '8697947664', '1507219704', '7652731314', '4718565953', '4427418816', '4414603918', '9641959361', '7997640368', '8368566800', '1913979284', '2677004727', '6256210439', '5449804993', '5324634234', '7153553492', '5305821365', '1775729480', '2944469928', '7636545669', '1076682543', '7902277106', '8725279362', '8638326204', '7883681562', '4830309918', '5168582986', '7079507033', '7008363161', '9391425334', '4033594085', '1181577747', '5643789204', '7194648907', '5596963937', '8652974884', '1158680681', '5905426474', '9315874047', '8808092456', '1437740590', '1980447844', '5385948464', '5481211928', '8048364176', '8317079318', '8894727133', '8950841751', '5727312516', '7653538731', '5260395623', '2055158184', '3507344855', '4143834440', '1119144035', '3303736528', '5543791114', '8847228380', '3407444652', '2010858735', '8676621406', '3602460396', '3924629577', '5033784069', '6986394311', '6508276876', '2376534971', '1236436471', '7162590027', '4234305823', '4943932774', '3484811464', '9517338753', '7491622727', '9469342557', '5429001474', '1086771272', '9050771087', '1131954238', '7067472045']
2017-03-01 12:43:25,009  - INFO - no. of Yaml files:84
2017-03-01 12:43:25,087  - INFO - starting for this account id :2809296861
2017-03-01 12:43:25,093  - INFO - starting for this account id :7813355720
2017-03-01 12:43:25,105  - INFO - starting for this account id :4804168647
2017-03-01 12:43:25,112  - INFO - starting for this account id :2231303651
2017-03-01 12:43:25,113  - INFO - starting for this account id :5689562067
2017-03-01 12:43:25,120  - INFO - starting for this account id :1507219704
2017-03-01 12:43:25,124  - INFO - starting for this account id :7652731314
2017-03-01 12:43:25,130  - INFO - starting for this account id :8697947664
2017-03-01 12:43:25,132  - INFO - starting for this account id :4718565953
2017-03-01 12:43:25,136  - INFO - starting for this account id :2677004727
2017-03-01 12:43:25,140  - INFO - starting for this account id :4427418816
2017-03-01 12:43:25,144  - INFO - starting for this account id :1913979284
2017-03-01 12:43:25,144  - INFO - starting for this account id :6256210439
2017-03-01 12:43:25,148  - INFO - starting for this account id :5449804993
2017-03-01 12:43:25,155  - INFO - starting for this account id :4414603918
2017-03-01 12:43:25,160  - INFO - starting for this account id :7153553492
2017-03-01 12:43:25,162  - INFO - starting for this account id :5324634234
2017-03-01 12:43:25,172  - INFO - starting for this account id :8368566800
2017-03-01 12:43:25,164  - INFO - starting for this account id :9641959361
2017-03-01 12:43:25,169  - INFO - starting for this account id :7997640368
2017-03-01 12:43:25,184  - INFO - starting for this account id :2944469928
2017-03-01 12:43:25,186  - INFO - starting for this account id :1775729480
2017-03-01 12:43:25,188  - INFO - starting for this account id :7636545669
2017-03-01 12:43:25,198  - INFO - starting for this account id :5305821365
2017-03-01 12:43:25,200  - INFO - starting for this account id :1076682543
2017-03-01 12:43:25,216  - INFO - starting for this account id :8725279362
2017-03-01 12:43:25,220  - INFO - starting for this account id :7902277106
2017-03-01 12:43:25,236  - INFO - starting for this account id :8638326204
2017-03-01 12:43:25,267  - INFO - starting for this account id :7883681562
2017-03-01 12:43:25,278  - INFO - starting for this account id :4830309918
2017-03-01 12:43:25,299  - INFO - starting for this account id :7079507033
2017-03-01 12:43:25,303  - INFO - starting for this account id :5168582986
2017-03-01 12:43:25,328  - INFO - starting for this account id :7008363161
2017-03-01 12:43:25,340  - INFO - starting for this account id :9391425334
2017-03-01 12:43:25,348  - INFO - starting for this account id :4033594085
2017-03-01 12:43:25,353  - INFO - starting for this account id :1181577747
2017-03-01 12:43:25,356  - INFO - starting for this account id :5643789204
2017-03-01 12:43:25,359  - INFO - starting for this account id :5596963937
2017-03-01 12:43:25,375  - INFO - starting for this account id :8652974884
2017-03-01 12:43:25,376  - INFO - starting for this account id :5481211928
2017-03-01 12:43:25,382  - INFO - starting for this account id :7194648907
2017-03-01 12:43:25,383  - INFO - starting for this account id :5905426474
2017-03-01 12:43:25,384  - INFO - starting for this account id :8048364176
2017-03-01 12:43:25,384  - INFO - starting for this account id :8894727133
2017-03-01 12:43:25,388  - INFO - starting for this account id :1158680681
2017-03-01 12:43:25,388  - INFO - starting for this account id :8317079318
2017-03-01 12:43:25,392  - INFO - starting for this account id :5385948464
2017-03-01 12:43:25,392  - INFO - starting for this account id :8950841751
2017-03-01 12:43:25,396  - INFO - starting for this account id :1437740590
2017-03-01 12:43:25,396  - INFO - starting for this account id :9315874047
2017-03-01 12:43:25,398  - INFO - starting for this account id :8808092456
2017-03-01 12:43:25,400  - INFO - starting for this account id :1980447844
2017-03-01 12:43:25,420  - INFO - starting for this account id :5727312516
2017-03-01 12:43:25,452  - INFO - starting for this account id :7653538731
2017-03-01 12:43:25,456  - INFO - starting for this account id :5260395623
2017-03-01 12:43:25,480  - INFO - starting for this account id :3507344855
2017-03-01 12:43:25,486  - INFO - starting for this account id :2055158184
2017-03-01 12:43:25,504  - INFO - starting for this account id :4143834440
2017-03-01 12:43:25,507  - INFO - starting for this account id :1119144035
2017-03-01 12:43:25,514  - INFO - starting for this account id :3303736528
2017-03-01 12:43:25,530  - INFO - starting for this account id :5543791114
2017-03-01 12:43:25,543  - INFO - starting for this account id :8847228380
2017-03-01 12:43:25,550  - INFO - starting for this account id :3407444652
2017-03-01 12:43:25,556  - INFO - starting for this account id :3924629577
2017-03-01 12:43:25,556  - INFO - starting for this account id :2010858735
2017-03-01 12:43:25,570  - INFO - starting for this account id :5033784069
2017-03-01 12:43:25,572  - INFO - starting for this account id :3602460396
2017-03-01 12:43:25,576  - INFO - starting for this account id :6986394311
2017-03-01 12:43:25,584  - INFO - starting for this account id :8676621406
2017-03-01 12:43:25,587  - INFO - starting for this account id :6508276876
2017-03-01 12:43:25,593  - INFO - starting for this account id :2376534971
2017-03-01 12:43:25,600  - INFO - starting for this account id :1236436471
2017-03-01 12:43:25,604  - INFO - starting for this account id :7162590027
2017-03-01 12:43:25,620  - INFO - starting for this account id :4943932774
2017-03-01 12:43:25,631  - INFO - starting for this account id :4234305823
2017-03-01 12:43:25,640  - INFO - starting for this account id :3484811464
2017-03-01 12:43:25,662  - INFO - starting for this account id :9517338753
2017-03-01 12:43:25,664  - INFO - starting for this account id :7491622727
2017-03-01 12:43:25,668  - INFO - starting for this account id :9469342557
2017-03-01 12:43:25,683  - INFO - starting for this account id :5429001474
2017-03-01 12:43:25,688  - INFO - starting for this account id :1086771272
2017-03-01 12:43:25,688  - INFO - starting for this account id :7067472045
2017-03-01 12:43:25,700  - INFO - starting for this account id :1131954238
2017-03-01 12:43:25,704  - INFO - starting for this account id :9050771087
2017-03-01 12:43:32,913  - INFO - This process is complete
2017-03-01 12:43:32,947  - INFO - This process is complete
2017-03-01 12:43:33,294  - INFO - This process is complete
2017-03-01 12:43:33,353  - INFO - This process is complete
2017-03-01 12:43:33,393  - INFO - This process is complete
2017-03-01 12:43:33,523  - INFO - This process is complete
2017-03-01 12:43:33,531  - INFO - This process is complete
2017-03-01 12:43:33,645  - INFO - This process is complete
2017-03-01 12:43:33,790  - INFO - This process is complete
2017-03-01 12:43:33,992  - INFO - This process is complete
2017-03-01 12:43:34,124  - INFO - This process is complete
2017-03-01 12:43:34,215  - INFO - This process is complete
2017-03-01 12:43:34,334  - INFO - This process is complete
2017-03-01 12:43:34,494  - INFO - This process is complete
2017-03-01 12:43:34,510  - INFO - This process is complete
2017-03-01 12:43:34,717  - INFO - This process is complete
2017-03-01 12:43:34,766  - INFO - This process is complete
2017-03-01 12:43:34,774  - INFO - This process is complete
2017-03-01 12:43:35,046  - INFO - This process is complete
2017-03-01 12:43:35,206  - INFO - This process is complete
2017-03-01 12:43:35,209  - INFO - This process is complete
2017-03-01 12:43:35,482  - INFO - This process is complete
2017-03-01 12:43:35,524  - INFO - This process is complete
2017-03-01 12:43:35,533  - INFO - This process is complete
2017-03-01 12:43:35,815  - INFO - This process is complete
2017-03-01 12:43:35,929  - INFO - This process is complete
2017-03-01 12:43:36,137  - INFO - This process is complete
2017-03-01 12:43:36,605  - INFO - This process is complete
2017-03-01 12:43:36,821  - INFO - This process is complete
2017-03-01 12:43:36,996  - INFO - This process is complete
2017-03-01 12:43:37,007  - INFO - This process is complete
2017-03-01 12:43:37,135  - INFO - This process is complete
2017-03-01 12:43:37,135  - INFO - This process is complete
2017-03-01 12:43:37,138  - INFO - This process is complete
2017-03-01 12:43:37,295  - INFO - This process is complete
2017-03-01 12:43:37,572  - INFO - This process is complete
2017-03-01 12:43:37,872  - INFO - This process is complete
2017-03-01 12:43:38,027  - INFO - This process is complete
2017-03-01 12:43:38,448  - INFO - This process is complete
2017-03-01 12:43:38,541  - INFO - This process is complete
2017-03-01 12:43:38,801  - INFO - This process is complete
2017-03-01 12:43:38,940  - INFO - This process is complete
2017-03-01 12:43:39,521  - INFO - This process is complete
2017-03-01 12:43:39,679  - INFO - This process is complete
2017-03-01 12:43:39,780  - INFO - This process is complete
2017-03-01 12:43:39,990  - INFO - This process is complete
2017-03-01 12:43:40,555  - INFO - This process is complete
2017-03-01 12:43:40,597  - INFO - This process is complete
2017-03-01 12:43:40,963  - INFO - This process is complete
2017-03-01 12:43:41,257  - INFO - This process is complete
2017-03-01 12:43:41,614  - INFO - This process is complete
2017-03-01 12:43:41,695  - INFO - This process is complete
2017-03-01 12:43:41,700  - INFO - This process is complete
2017-03-01 12:43:42,095  - INFO - This process is complete
2017-03-01 12:43:42,399  - INFO - This process is complete
2017-03-01 12:43:42,997  - ERROR - error occured for 1086771272 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,000  - ERROR - error occured for 8808092456 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:42,997  - ERROR - error occured for 9517338753 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,001  - ERROR - error occured for 7902277106 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,093  - INFO - This process is complete
2017-03-01 12:43:43,093  - INFO - This process is complete
2017-03-01 12:43:43,093  - INFO - This process is complete
2017-03-01 12:43:43,093  - INFO - This process is complete
2017-03-01 12:43:43,000  - ERROR - error occured for 4804168647 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:42,999  - ERROR - error occured for 8725279362 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,101  - INFO - This process is complete
2017-03-01 12:43:43,101  - INFO - This process is complete
2017-03-01 12:43:43,002  - ERROR - error occured for 9391425334 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,105  - INFO - This process is complete
2017-03-01 12:43:43,002  - ERROR - error occured for 2231303651 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,108  - INFO - This process is complete
2017-03-01 12:43:43,003  - ERROR - error occured for 8950841751 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,003  - ERROR - error occured for 8652974884 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,113  - INFO - This process is complete
2017-03-01 12:43:43,003  - ERROR - error occured for 7813355720 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,004  - ERROR - error occured for 8317079318 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,114  - INFO - This process is complete
2017-03-01 12:43:43,003  - ERROR - error occured for 9469342557 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,114  - INFO - This process is complete
2017-03-01 12:43:43,114  - INFO - This process is complete
2017-03-01 12:43:43,006  - ERROR - error occured for 8368566800 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,117  - INFO - This process is complete
2017-03-01 12:43:43,113  - INFO - This process is complete
2017-03-01 12:43:43,004  - ERROR - error occured for 5033784069 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,121  - INFO - This process is complete
2017-03-01 12:43:42,997  - ERROR - error occured for 5429001474 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,122  - INFO - This process is complete
2017-03-01 12:43:43,007  - ERROR - error occured for 5305821365 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,123  - INFO - This process is complete
2017-03-01 12:43:42,998  - ERROR - error occured for 4143834440 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,127  - INFO - This process is complete
2017-03-01 12:43:43,006  - ERROR - error occured for 1236436471 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,129  - INFO - This process is complete
2017-03-01 12:43:43,006  - ERROR - error occured for 3303736528 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,133  - INFO - This process is complete
2017-03-01 12:43:42,999  - ERROR - error occured for 7636545669 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,134  - INFO - This process is complete
2017-03-01 12:43:43,008  - ERROR - error occured for 5385948464 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,137  - INFO - This process is complete
2017-03-01 12:43:43,005  - ERROR - error occured for 7491622727 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1495, in _DownloadReport
    response = self._DownloadReportAsStream(post_body, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1546, in _DownloadReportAsStream
    return self.url_opener.open(request)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
2017-03-01 12:43:43,139  - INFO - This process is complete
2017-03-01 12:43:43,002  - ERROR - error occured for 4718565953 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1495, in _DownloadReport
    response = self._DownloadReportAsStream(post_body, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1546, in _DownloadReportAsStream
    return self.url_opener.open(request)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:42,999  - ERROR - error occured for 7653538731 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1495, in _DownloadReport
    response = self._DownloadReportAsStream(post_body, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1546, in _DownloadReportAsStream
    return self.url_opener.open(request)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,144  - INFO - This process is complete
2017-03-01 12:43:43,144  - INFO - This process is complete
2017-03-01 12:43:43,006  - ERROR - error occured for 8048364176 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,147  - INFO - This process is complete
2017-03-01 12:43:43,007  - ERROR - error occured for 5643789204 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 12:43:43,149  - INFO - This process is complete
2017-03-01 12:43:46,577  - ERROR - error occured for 5543791114 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1495, in _DownloadReport
    response = self._DownloadReportAsStream(post_body, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1546, in _DownloadReportAsStream
    return self.url_opener.open(request)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
KeyboardInterrupt
2017-03-01 12:43:46,586  - INFO - This process is complete
2017-03-01 12:43:46,577  - ERROR - error occured for 4943932774 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1495, in _DownloadReport
    response = self._DownloadReportAsStream(post_body, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1546, in _DownloadReportAsStream
    return self.url_opener.open(request)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/shubham/anaconda2/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
KeyboardInterrupt
2017-03-01 12:43:46,590  - INFO - This process is complete
2017-03-01 13:10:19,098  - INFO - url of sheet which we are hitting {'https://docs.google.com/spreadsheets/d/1TnhTtkISzPJvWOL06PnsVet7lcJEBbqjF7SeXLXH4jo/edit#gid=0': {'NOMBRE': 'test2'}}
2017-03-01 13:10:19,098  - INFO - URL from which we are getting list of accounts:{'https://docs.google.com/spreadsheets/d/1TnhTtkISzPJvWOL06PnsVet7lcJEBbqjF7SeXLXH4jo/edit#gid=0': {'NOMBRE': 'test2'}}
2017-03-01 13:10:21,863  - INFO - Connected to drive
2017-03-01 13:10:21,863  - INFO - Connected to google drive

2017-03-01 13:10:24,959  - INFO - List of accounts ['2809296861', '7813355720', '4804168647', '2231303651', '5689562067', '8697947664', '1507219704', '7652731314', '4718565953', '4427418816', '4414603918', '9641959361', '7997640368', '8368566800', '1913979284', '2677004727', '6256210439', '5449804993', '5324634234', '7153553492', '5305821365', '1775729480', '2944469928', '7636545669', '1076682543', '7902277106', '8725279362', '8638326204', '7883681562', '4830309918', '5168582986', '7079507033', '7008363161', '9391425334', '4033594085', '1181577747', '5643789204', '7194648907', '5596963937', '8652974884', '1158680681', '5905426474', '9315874047', '8808092456', '1437740590', '1980447844', '5385948464', '5481211928', '8048364176', '8317079318', '8894727133', '8950841751', '5727312516', '7653538731', '5260395623', '2055158184', '3507344855', '4143834440', '1119144035', '3303736528', '5543791114', '8847228380', '3407444652', '2010858735', '8676621406', '3602460396', '3924629577', '5033784069', '6986394311', '6508276876', '2376534971', '1236436471', '7162590027', '4234305823', '4943932774', '3484811464', '9517338753', '7491622727', '9469342557', '5429001474', '1086771272', '9050771087', '1131954238', '7067472045']
2017-03-01 13:10:24,959  - INFO - no. of Yaml files:84
2017-03-01 13:10:24,963  - INFO - starting for this account id :2809296861
2017-03-01 13:10:24,970  - INFO - starting for this account id :4804168647
2017-03-01 13:10:24,976  - INFO - starting for this account id :7813355720
2017-03-01 13:10:24,980  - INFO - starting for this account id :4414603918
2017-03-01 13:10:24,988  - INFO - starting for this account id :9641959361
2017-03-01 13:10:24,988  - INFO - starting for this account id :5689562067
2017-03-01 13:10:24,990  - INFO - starting for this account id :2231303651
2017-03-01 13:10:25,003  - INFO - starting for this account id :4718565953
2017-03-01 13:10:25,003  - INFO - starting for this account id :8697947664
2017-03-01 13:10:25,004  - INFO - starting for this account id :7997640368
2017-03-01 13:10:25,008  - INFO - starting for this account id :8368566800
2017-03-01 13:10:25,008  - INFO - starting for this account id :1507219704
2017-03-01 13:10:25,012  - INFO - starting for this account id :1913979284
2017-03-01 13:10:25,012  - INFO - starting for this account id :7652731314
2017-03-01 13:10:25,016  - INFO - starting for this account id :4427418816
2017-03-01 13:10:25,023  - INFO - starting for this account id :2677004727
2017-03-01 13:10:25,028  - INFO - starting for this account id :1076682543
2017-03-01 13:10:25,032  - INFO - starting for this account id :7636545669
2017-03-01 13:10:25,036  - INFO - starting for this account id :8725279362
2017-03-01 13:10:25,038  - INFO - starting for this account id :7902277106
2017-03-01 13:10:25,048  - INFO - starting for this account id :8638326204
2017-03-01 13:10:25,048  - INFO - starting for this account id :7883681562
2017-03-01 13:10:25,051  - INFO - starting for this account id :5449804993
2017-03-01 13:10:25,057  - INFO - starting for this account id :6256210439
2017-03-01 13:10:25,074  - INFO - starting for this account id :5324634234
2017-03-01 13:10:25,076  - INFO - starting for this account id :5305821365
2017-03-01 13:10:25,080  - INFO - starting for this account id :1775729480
2017-03-01 13:10:25,083  - INFO - starting for this account id :4830309918
2017-03-01 13:10:25,084  - INFO - starting for this account id :2944469928
2017-03-01 13:10:25,090  - INFO - starting for this account id :7153553492
2017-03-01 13:10:25,091  - INFO - starting for this account id :5168582986
2017-03-01 13:10:25,114  - INFO - starting for this account id :7079507033
2017-03-01 13:10:25,144  - INFO - starting for this account id :7008363161
2017-03-01 13:10:25,155  - INFO - starting for this account id :9391425334
2017-03-01 13:10:25,204  - INFO - starting for this account id :1181577747
2017-03-01 13:10:25,197  - INFO - starting for this account id :4033594085
2017-03-01 13:10:25,220  - INFO - starting for this account id :5643789204
2017-03-01 13:10:25,224  - INFO - starting for this account id :7194648907
2017-03-01 13:10:25,236  - INFO - starting for this account id :5596963937
2017-03-01 13:10:25,240  - INFO - starting for this account id :1158680681
2017-03-01 13:10:25,244  - INFO - starting for this account id :5905426474
2017-03-01 13:10:25,244  - INFO - starting for this account id :8652974884
2017-03-01 13:10:25,248  - INFO - starting for this account id :9315874047
2017-03-01 13:10:25,252  - INFO - starting for this account id :8808092456
2017-03-01 13:10:25,264  - INFO - starting for this account id :1437740590
2017-03-01 13:10:25,272  - INFO - starting for this account id :1980447844
2017-03-01 13:10:25,292  - INFO - starting for this account id :5385948464
2017-03-01 13:10:25,310  - INFO - starting for this account id :5481211928
2017-03-01 13:10:25,316  - INFO - starting for this account id :8048364176
2017-03-01 13:10:25,322  - INFO - starting for this account id :8317079318
2017-03-01 13:10:25,328  - INFO - starting for this account id :8950841751
2017-03-01 13:10:25,336  - INFO - starting for this account id :5727312516
2017-03-01 13:10:25,324  - INFO - starting for this account id :8894727133
2017-03-01 13:10:25,344  - INFO - starting for this account id :7653538731
2017-03-01 13:10:25,354  - INFO - starting for this account id :5260395623
2017-03-01 13:10:25,365  - INFO - starting for this account id :2055158184
2017-03-01 13:10:25,380  - INFO - starting for this account id :3507344855
2017-03-01 13:10:25,399  - INFO - starting for this account id :4143834440
2017-03-01 13:10:25,405  - INFO - starting for this account id :1119144035
2017-03-01 13:10:25,408  - INFO - starting for this account id :8847228380
2017-03-01 13:10:25,410  - INFO - starting for this account id :5543791114
2017-03-01 13:10:25,418  - INFO - starting for this account id :3303736528
2017-03-01 13:10:25,424  - INFO - starting for this account id :3407444652
2017-03-01 13:10:25,423  - INFO - starting for this account id :8676621406
2017-03-01 13:10:25,428  - INFO - starting for this account id :2010858735
2017-03-01 13:10:25,448  - INFO - starting for this account id :3602460396
2017-03-01 13:10:25,452  - INFO - starting for this account id :5033784069
2017-03-01 13:10:25,454  - INFO - starting for this account id :6986394311
2017-03-01 13:10:25,455  - INFO - starting for this account id :3924629577
2017-03-01 13:10:25,489  - INFO - starting for this account id :6508276876
2017-03-01 13:10:25,497  - INFO - starting for this account id :2376534971
2017-03-01 13:10:25,508  - INFO - starting for this account id :1236436471
2017-03-01 13:10:25,512  - INFO - starting for this account id :7162590027
2017-03-01 13:10:25,532  - INFO - starting for this account id :9517338753
2017-03-01 13:10:25,536  - INFO - starting for this account id :4234305823
2017-03-01 13:10:25,540  - INFO - starting for this account id :7491622727
2017-03-01 13:10:25,540  - INFO - starting for this account id :4943932774
2017-03-01 13:10:25,543  - INFO - starting for this account id :9469342557
2017-03-01 13:10:25,544  - INFO - starting for this account id :3484811464
2017-03-01 13:10:25,555  - INFO - starting for this account id :9050771087
2017-03-01 13:10:25,560  - INFO - starting for this account id :1131954238
2017-03-01 13:10:25,563  - INFO - starting for this account id :5429001474
2017-03-01 13:10:25,568  - INFO - starting for this account id :1086771272
2017-03-01 13:10:25,576  - INFO - starting for this account id :7067472045
2017-03-01 13:10:30,894  - INFO - This process is complete
2017-03-01 13:10:30,912  - INFO - This process is complete
2017-03-01 13:10:31,127  - INFO - This process is complete
2017-03-01 13:10:31,163  - INFO - This process is complete
2017-03-01 13:10:31,349  - INFO - This process is complete
2017-03-01 13:10:31,778  - INFO - This process is complete
2017-03-01 13:10:31,886  - INFO - This process is complete
2017-03-01 13:10:31,969  - INFO - This process is complete
2017-03-01 13:10:32,464  - INFO - This process is complete
2017-03-01 13:10:32,684  - INFO - This process is complete
2017-03-01 13:10:32,784  - INFO - This process is complete
2017-03-01 13:10:32,980  - INFO - This process is complete
2017-03-01 13:10:33,063  - INFO - This process is complete
2017-03-01 13:10:33,304  - INFO - This process is complete
2017-03-01 13:10:33,354  - INFO - This process is complete
2017-03-01 13:10:33,357  - INFO - This process is complete
2017-03-01 13:10:33,382  - INFO - This process is complete
2017-03-01 13:10:33,403  - INFO - This process is complete
2017-03-01 13:10:33,637  - INFO - This process is complete
2017-03-01 13:10:33,650  - INFO - This process is complete
2017-03-01 13:10:33,988  - INFO - This process is complete
2017-03-01 13:10:34,170  - INFO - This process is complete
2017-03-01 13:10:34,227  - INFO - This process is complete
2017-03-01 13:10:34,267  - INFO - This process is complete
2017-03-01 13:10:34,696  - INFO - This process is complete
2017-03-01 13:10:35,234  - INFO - This process is complete
2017-03-01 13:10:35,286  - INFO - This process is complete
2017-03-01 13:10:35,940  - INFO - This process is complete
2017-03-01 13:10:36,238  - INFO - This process is complete
2017-03-01 13:10:36,389  - INFO - This process is complete
2017-03-01 13:10:37,143  - INFO - This process is complete
2017-03-01 13:10:37,218  - INFO - This process is complete
2017-03-01 13:10:37,254  - INFO - This process is complete
2017-03-01 13:10:37,416  - INFO - This process is complete
2017-03-01 13:10:37,417  - INFO - This process is complete
2017-03-01 13:10:37,816  - INFO - This process is complete
2017-03-01 13:10:38,589  - INFO - This process is complete
2017-03-01 13:10:38,617  - INFO - This process is complete
2017-03-01 13:10:38,780  - INFO - This process is complete
2017-03-01 13:10:38,784  - INFO - This process is complete
2017-03-01 13:10:38,964  - INFO - This process is complete
2017-03-01 13:10:39,056  - INFO - This process is complete
2017-03-01 13:10:39,364  - INFO - This process is complete
2017-03-01 13:10:39,429  - INFO - This process is complete
2017-03-01 13:10:39,631  - INFO - This process is complete
2017-03-01 13:10:39,671  - INFO - This process is complete
2017-03-01 13:10:39,743  - INFO - This process is complete
2017-03-01 13:10:39,782  - INFO - This process is complete
2017-03-01 13:10:40,164  - INFO - This process is complete
2017-03-01 13:10:40,308  - INFO - This process is complete
2017-03-01 13:10:40,493  - INFO - This process is complete
2017-03-01 13:10:40,502  - INFO - This process is complete
2017-03-01 13:10:40,587  - INFO - This process is complete
2017-03-01 13:10:40,712  - INFO - This process is complete
2017-03-01 13:10:40,827  - INFO - This process is complete
2017-03-01 13:10:41,056  - INFO - This process is complete
2017-03-01 13:10:41,167  - INFO - This process is complete
2017-03-01 13:10:41,454  - INFO - This process is complete
2017-03-01 13:10:41,491  - INFO - This process is complete
2017-03-01 13:10:41,519  - INFO - This process is complete
2017-03-01 13:10:41,841  - INFO - This process is complete
2017-03-01 13:10:42,610  - INFO - This process is complete
2017-03-01 13:10:42,696  - INFO - This process is complete
2017-03-01 13:10:45,188  - INFO - This process is complete
2017-03-01 13:10:45,601  - ERROR - error occured for 7997640368 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,609  - INFO - This process is complete
2017-03-01 13:10:45,613  - ERROR - error occured for 4804168647 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,604  - ERROR - error occured for 1086771272 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,616  - INFO - This process is complete
2017-03-01 13:10:45,616  - INFO - This process is complete
2017-03-01 13:10:45,614  - ERROR - error occured for 7491622727 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,617  - INFO - This process is complete
2017-03-01 13:10:45,610  - ERROR - error occured for 4718565953 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,619  - INFO - This process is complete
2017-03-01 13:10:45,613  - ERROR - error occured for 4143834440 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,618  - ERROR - error occured for 3303736528 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,620  - INFO - This process is complete
2017-03-01 13:10:45,610  - ERROR - error occured for 8317079318 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,622  - INFO - This process is complete
2017-03-01 13:10:45,608  - ERROR - error occured for 1119144035 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,607  - ERROR - error occured for 7636545669 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,625  - INFO - This process is complete
2017-03-01 13:10:45,625  - INFO - This process is complete
2017-03-01 13:10:45,610  - ERROR - error occured for 8950841751 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,625  - INFO - This process is complete
2017-03-01 13:10:45,619  - INFO - This process is complete
2017-03-01 13:10:45,601  - ERROR - error occured for 5643789204 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,601  - ERROR - error occured for 8048364176 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,627  - INFO - This process is complete
2017-03-01 13:10:45,628  - INFO - This process is complete
2017-03-01 13:10:45,606  - ERROR - error occured for 3484811464 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,630  - INFO - This process is complete
2017-03-01 13:10:45,602  - ERROR - error occured for 8725279362 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,630  - INFO - This process is complete
2017-03-01 13:10:45,621  - ERROR - error occured for 7902277106 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,634  - INFO - This process is complete
2017-03-01 13:10:45,635  - ERROR - error occured for 9469342557 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,637  - INFO - This process is complete
2017-03-01 13:10:45,641  - ERROR - error occured for 5305821365 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,643  - INFO - This process is complete
2017-03-01 13:10:45,643  - ERROR - error occured for 8652974884 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,649  - INFO - This process is complete
2017-03-01 13:10:45,649  - ERROR - error occured for 9517338753 
Traceback (most recent call last):
  File "keywords_bak.py", line 87, in filegenerator
    GetKeywordURLs(account)
  File "keywords_bak.py", line 81, in GetKeywordURLs
    skip_report_summary=True, include_zero_impressions=True)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/common.py", line 486, in Wrapper
    return utility_method(*args, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1225, in DownloadReport
    output, **kwargs)
  File "/home/shubham/anaconda2/lib/python2.7/site-packages/googleads/adwords.py", line 1499, in _DownloadReport
    else response.read())
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/home/shubham/anaconda2/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/home/shubham/anaconda2/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/shubham/anaconda2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
2017-03-01 13:10:45,651  - INFO - This process is complete
